travis:
  secure:
    BINSTAR_TOKEN: BlEqC/bxhgZgPU3261jqJXyzGoxyGfrFVou8UVSVkvl/8L892PEP9n1RN2ub7fG2lK6pz6GbreCJLEVrPW4WYp5TZitkV9Fz3uu9TIsbFFu3HCltFyGV/J8GoDAAxxIcIfy3BImBI+OoXKszMruf9mrVAC7oyfeidvEjnjybbe5bkOXDqPM2t4Ab3fSe0nKLUeX0BL3iih3VHfCZi5KuBX+sdT2u87y++JNWh7lvk1g5c+8oNqBFEc0xxOsLprAo46qWkMVLa73rxTneCKBoAPxyXVgc2AUivT9CdaEmOOWdSgRDK3l03CF49eMP43YcIZDG0GGSO5qIbU+7XQJ2ztMZepF6tU4sEIMw3Y/b8D7O50XkCUJ4nVDZStsrGJIqiZInruREreyaJeBbKyE7VcgOC7zZh+yNpdjEBmxxskEJ0UYYlWV47b5OdYCVNpkXUSpNPBowotAfqQylEYPeDzQ4GZrwzUmNrxRh2tx1oB7Wf9tiGFSqtrwohXHT5cmgfeY+Jj4+HpVS/aDWxP/5pT11AYmznhzurBR4pMIt4ypyljfOURv121UaM83wikqT6ZUXi2wYgilnVykSXWnUbu96Ce4FlFxtd45m4HSiDk3DYwsrpKtE1CCB41uuFa8x8gt0WmUIBGqSlbHhBPsKif3FbmsP/QuQ9/Vo9lOlNaM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
