travis:
  secure:
    BINSTAR_TOKEN: FkNZAutRja4ifurP/ei4kubvzG4yXXPCydHWQDu7f8Fc/UCcXSwjnirp2rqL1GhwLSWq62uYbYSgkDWaMQGl//g45PdmSn0Ue8FZMNkP7+IsPA9EZUdtUgCKddtdUdKWNKouszHlbId+KnvFjCX6OlkMWxjUzzczpPAlUSUGErpk9dejcHa4m2BJZN9TeCtc6Gsn9XpzTGgarFmUZXLQrCjD2sk0WO7RWEU9NGVdz/fiTmTzS+Cm3z0OOkx1WtgTTFmXCTx3+j1uxwAZgeDAfRhV95Qd0libgPSS9dL+q5IYEgsgU/DCBDRy5GJt1CUhBJPgpx4cR4LKvaTVgf56CrGeXycKjETZsF+ihMrf+n8qJjX+FtlV4usujyDL07io+E3GPKfR3UjZfBU9CHNreHCKe4IYUo64LPSFbVwoV9C/ApB4DrKd5GXAWj77yNgnVC2T0OY6K9ZH6YUNAohrjNzfiPoCWfk/PYwyWIGixtmkfaLvBA/VO6cJw99w2We+qJ7HhHSMrFcBydshuQvF6h9J5W7IN5p76dYG9NiD+BabTpf44AE5Y45SwoO018f0j22pJNCADrrL70Gi7q+WB9OZsYdphoCIs8hM/5eixIWrg5BJsBdwO7fULGj36j9NXeFqZlu59YVFbMQBO2Q4CkhwRucppUAtAeijnacjhPs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
